blog/cms/blog/urls.py
from django.cgionf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.list_of_post),
    url(r'^(?P<slug>[-\w]+)/$', views.post_detail, name = 'post_detail'),
    url(r'^category/(?P<category_slug>[-\w]+)/$',views.list_of_post_by_category, name='list_of_post_by_category'),
    url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name = 'add_comment'),
]

blog/cms/cms/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


# from blog import urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/cms/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
# Create your models here.

#Category
class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def get_absolute_url(self):
        return reverse('blog:list_of_post_by_category',args=[self.slug])

    def __str__(self):
        return self.name

#Post
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    content = models.TextField()
    seo_title = models.CharField(max_length=160)
    seo_description = models.CharField(max_length=160)
    author = models.ForeignKey(User, related_name='blog_posts')
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # seo_title = models.CharField(max_length=250)
	# seo_description = models.CharField(max_length=160)
	#author = models.ForeignKey(User, related_name='blog_posts')
	#published = models.DateTimeField(default=timezone.now)
	#created = models.DateTimeField(auto_now_add=True)
	#updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='draft')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post , related_name='all_comments')
    user = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

    def approved(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.user

blog/cms/blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('user', 'email', 'body')

blog/cms/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Category
from .forms import CommentForm
# Create your views here.

def list_of_post_by_category(request, category_slug):
    categories = Category.objects.all()
    post = Post.objects.filter(status='published')
    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        post = post.filter(category=category)
    template = 'blog/category/list_of_posts_by_category.html'
    context = {'categories' : categories, 'post': post, 'category' : category}
    return render(request, template, context)


def list_of_post(request):
    post = Post.objects.filter(status='published')
    template = 'blog/post/list_of_post.html'
    context = {'post':post}
    return render(request, template, context)
    #return render(request, 'blog/post/list_of_post.html', {'post':post})


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    template = 'blog/post/post_detail.html'
    context = {'post':post}
    return render(request, template, context)

def add_comment(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', slug=post.slug)
    else:
        form = CommentForm()
    template = 'blog/post/add_comment.html'
    context = {'form': form}
    return render(request, template, context)

blog/cms/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!--The above 3 meta tags *must* come first in the head-->
    <!--any other head content *must* come after these tags-->
    <meta name="description" content="{% block description %} {% endblock %}">
    <meta name="author" content="">
    <meta rel="icon" href="">
    <title>{% block title %}{% endblock %}</title>
    <!--CSS Style-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/ie10-viewport-bug-workaround.css'%}">
    <!--JS-->
    <script type="text/javascript" src="{% static 'js/ie-emulation-modes-warning.js'%}"></script>
</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script type="text/javascript" src="{% static 'js/ie-emulation-modes-warning.js'%}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/ie10-viewport-bug-workaround.js'%}"></script>
</body>

</html>

blog/cms/blog/templates/blog/category/list_of_posts_by_category.html
{% extends 'blog/base.html' %}

{% block description %} This is a category {% endblock %}
{% block title %} {{ category.name}} {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <div class="page-header">
           <h1>Our latest post in {{ category.name}}</h1>
        </div>

        {% for posts in post %}
            <h2> <a href="{{posts.get_absolute_url}}"> {{ posts.title }}  </a> </h2>
            <small> Written by {{ posts.author }} on {{posts.published}}
            </small>
            {{posts.content|truncatewords:40|linebreaks}}
        {% endfor %}
    </div>

    <div class="col-md-4">
        <div class="page-header">
           <h1>Sidebar</h1>
        </div>
    </div>
</div>
{% endblock %}

blog/cms/blog/templates/blog/post/add_comment.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h1>Add new Comment</h1>
    <form method="POST"> {% csrf_token %}
        {{ form|crispy}}
    <button type="submit" class="btn btn-success">Submit</button>
    </form>


{% endblock %}

blog/cms/blog/templates/blog/post/list_of_post.html
{% extends 'blog/base.html' %}

{% block description %} This is the description {% endblock %}
{% block title %} List of blog post{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <div class="page-header">
           <h1>Our latest post</h1>
        </div>

        {% for posts in post %}
            <h2> <a href="{{posts.get_absolute_url}}"> {{ posts.title }}  </a> </h2>
            <small> Written by {{ posts.author }} on {{posts.published}} in
                <a href="{{posts.category.get_absolute_url}}"> {{posts.category}}</a>
            </small>
            {{posts.content|truncatewords:40|linebreaks}}
        {% endfor %}
    </div>

    <div class="col-md-4">
        <div class="page-header">
           <h1>Sidebar</h1>
        </div>
    </div>
</div>
{% endblock %}

blog/cms/blog/templates/blog/post/post_detail.html
{% extends 'blog/base.html' %}

{% block description %} {{ post.description}}{% endblock %}
{% block title %} {{ post.seo_title}}{% endblock %}

{% block content %}
<div class="row">
        <div class="col-md-8">
        <div class="page-header">
           <h1>{{ post.title}}</h1>
        </div>
        <small> Written by {{ post.author }} on {{post.published}}
            in
            <a href="{{ post.category.get_absolute_url}}">{{post.category}}</a></small>
        <hr>
        {{post.content|linebreaks}}
        <hr>
        <h1>Leave a comment</h1>
        <p> Total number of Comments {{ post.all_comments.count }} </p>
        <a href="{% url 'blog:add_comment' slug=post.slug%}"/> write comment here </a>

        {% for comment in post.all_comments.all %}

            <p>{{ comment.created }}</p>
            <p>{{ comment.user}}</p>
            <p>{{ comment.body}}</p>
        {% empty %}
            <p>There is no comments</p>
        {% endfor %}
            </div>
</div>
{% endblock %}